Add/readme/clustering
GrupoTuringCodes/Arvore-de-Habilidades pull request #51
Opened 2020-06-12 02:30 UTC by nelsonayamashita

Adicionei readme do Clustering.
O arquivo original era um pdf bem grande e completo, peguei só a introdução.

2020-06-15 20:43 UTC, arielguerreiro requested changes

2020-06-15 20:43 UTC, arielguerreiro commented on Machine Learning/Unsupervised Learning/Clustering/README.md
> +    - [Slides de uma aula sobre Clustering](https://cs.wmich.edu/alfuqaha/summer14/cs6530/lectures/ClusteringAnalysis.pdf)
Melhor colocar a referência de qual aula que foi a retirada, para garantir que estamos dando crédito corretamente

2020-06-16 01:11 UTC, AZANK7173 approved these changes

2020-06-16 01:11 UTC, AZANK7173 approved these changes

2020-06-16 01:41 UTC, arielguerreiro approved these changes

2020-06-16 01:41 UTC, merged